export const ActionType = {
  FETCH_APARTMENTS_START: 'FETCH_APARTMENTS_START',
  FETCH_APARTMENTS_SUCCESS: 'FETCH_APARTMENTS_SUCCESS',
  FETCH_APARTMENTS_FAIL: 'FETCH_APARTMENTS_FAIL',

  UPDATE_APARTMENT: 'UPDATE_APARTMENT',
};